run:
  timeout: 1m
linters:
  enable-all: true
  disable:
    - testpackage
    - paralleltest
    - gomnd
    - gochecknoglobals
    - nlreturn
    - wsl
    - gci
    - gofumpt
    - depguard
    - varnamelen
    - exhaustruct
    - wrapcheck
    - lll
    - funlen
    - gochecknoinits
    - cyclop
    - errname
    - dupl
    - exportloopref
    - execinquery
    - err113
